-- H2 2.4.240;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '18b1db73d832984b' HASH 'ea4358312474d66acd71d80e88e303641a6193fed7c29dbebd24d7994c4ab26e' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."CONCERTS"(
    "BOUGHT_MERCH" BOOLEAN NOT NULL,
    "CROWD_ENERGY_SCORE" INTEGER,
    "DANCED_ALL_NIGHT" BOOLEAN NOT NULL,
    "DATE_ATTENDED" DATE NOT NULL,
    "DURATION_MINUTES" INTEGER,
    "ENCORE_COUNT" INTEGER,
    "FIRST_TIME_SEEN" BOOLEAN NOT NULL,
    "MERCH_SPENT_EUR" NUMERIC(10, 2),
    "PHONE_FREE_SHOW" BOOLEAN NOT NULL,
    "PRODUCTION_SCORE" INTEGER,
    "RATING" INTEGER,
    "SETLIST_SCORE" INTEGER,
    "SONGS_PLAYED" INTEGER,
    "TEAR_JERKER" BOOLEAN NOT NULL,
    "TICKET_PRICE_EUR" NUMERIC(10, 2),
    "TRAVEL_COST_EUR" NUMERIC(10, 2),
    "VIBE_SCORE" INTEGER,
    "VOCAL_FORM_SCORE" INTEGER,
    "ADDED_BY_ID" BIGINT,
    "CREATED_AT" TIMESTAMP(6),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "UPDATED_AT" TIMESTAMP(6),
    "CITY" CHARACTER VARYING(100) NOT NULL,
    "COUNTRY" CHARACTER VARYING(100),
    "CREW_WITH" CHARACTER VARYING(200),
    "FAVORITE_SONG" CHARACTER VARYING(200),
    "MAIN_ARTIST" CHARACTER VARYING(200) NOT NULL,
    "MOOD_TAGS" CHARACTER VARYING(200),
    "TOUR_NAME" CHARACTER VARYING(200),
    "VENUE" CHARACTER VARYING(200) NOT NULL,
    "OPENING_ACTS" CHARACTER VARYING(300),
    "BEST_MOMENT" CHARACTER VARYING(500),
    "PERSONAL_NOTES" CHARACTER VARYING(2000),
    "SETLIST_NOTES" CHARACTER VARYING(2000),
    "GENRE" ENUM('ALT_ROCK', 'BEDROOM_POP', 'ELECTRONIC', 'EMO_REVIVAL', 'FOLK', 'HIP_HOP', 'HOUSE', 'HYPERPOP', 'INDIE_POP', 'INDIE_ROCK', 'JAZZ', 'JPOP', 'KPOP', 'METAL', 'POP', 'PUNK', 'RAP', 'RNB', 'ROCK', 'SHOEGAZE', 'SOUL', 'TECHNO') NOT NULL,
    "SECONDARY_GENRE" ENUM('ALT_ROCK', 'BEDROOM_POP', 'ELECTRONIC', 'EMO_REVIVAL', 'FOLK', 'HIP_HOP', 'HOUSE', 'HYPERPOP', 'INDIE_POP', 'INDIE_ROCK', 'JAZZ', 'JPOP', 'KPOP', 'METAL', 'POP', 'PUNK', 'RAP', 'RNB', 'ROCK', 'SHOEGAZE', 'SOUL', 'TECHNO'),
    "SHOW_TYPE" ENUM('ACOUSTIC_SET', 'AMPHITHEATER', 'ARENA_TOUR', 'CLUB_SHOW', 'FESTIVAL_SET', 'INTIMATE_VENUE', 'OUTDOOR_FREE', 'RESIDENCY', 'SECRET_SHOW', 'STADIUM_TOUR') NOT NULL,
    "VENUE_SIZE" ENUM('AMPHITHEATER', 'ARENA', 'DIVE_BAR', 'FESTIVAL_FIELD', 'LARGE_VENUE', 'MID_VENUE', 'SMALL_CLUB', 'STADIUM'),
    "VIEWING_AREA" ENUM('BALCONY', 'BARRICADE', 'FESTIVAL_FIELD', 'FRONT_PIT', 'GENERAL_ADMISSION', 'SEATED_FLOOR', 'SEATED_LOWER', 'SEATED_UPPER', 'STANDING_ONLY', 'VIP_BOX')
);     
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5CA8D_2" PRIMARY KEY("ID");             
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.CONCERTS;               
INSERT INTO "PUBLIC"."CONCERTS" VALUES
(TRUE, 10, TRUE, DATE '2024-06-21', 195, 3, TRUE, 85.00, FALSE, 10, 5, 10, 44, TRUE, 210.00, 320.00, 10, 9, 1, TIMESTAMP '2026-06-25 13:28:07.016387', 1, TIMESTAMP '2026-06-25 13:28:07.016387', 'London', 'UK', 'Mia, Hanna, Ema (all swifties since debut)', 'All Too Well (10 Minute Version)', 'Taylor Swift', 'Cathartic, generational, surreal, friendship bracelets traded', 'The Eras Tour', 'Wembley Stadium', 'Paramore', 'The Folklore set under the moss-covered cabin. The whole stadium silent then erupting.', U&'Worth every cent of the \20ac210 + travel. Wore the bejeweled outfit. Cried 4 times. Best show of my life.', '44 songs across 10 eras, surprise songs: Maroon (acoustic) + The Manuscript. The 1989 set was peak.', 'POP', 'INDIE_POP', 'STADIUM_TOUR', 'STADIUM', 'SEATED_FLOOR'),
(TRUE, 10, TRUE, DATE '2024-03-12', 115, 2, FALSE, 40.00, FALSE, 10, 5, 9, 22, TRUE, 75.00, 60.00, 10, 9, 1, TIMESTAMP '2026-06-25 13:28:07.027386', 2, TIMESTAMP '2026-06-25 13:28:07.027386', 'London', 'UK', 'Solo (queued 14 hours)', 'About You', 'The 1975', 'Theatrical, melancholy, intoxicating, fan-projection', 'Still... At Their Very Best', 'O2 Academy Brixton', 'Holly Humberstone', 'About You finale with confetti drop. Matty went off-script for two minutes. The set room with the TV.', 'Queued from 6am to get barricade. Worth it. Made friends in line.', 'The whole ''house'' set design is genius. I''m In Love With You was unhinged in the best way.', 'INDIE_POP', 'ALT_ROCK', 'ARENA_TOUR', 'LARGE_VENUE', 'BARRICADE'),
(FALSE, 9, FALSE, DATE '2024-09-08', 95, 2, TRUE, 35.00, FALSE, 8, 5, 10, 18, TRUE, 55.00, 40.00, 9, 10, 1, TIMESTAMP '2026-06-25 13:28:07.029386', 3, TIMESTAMP '2026-06-25 13:28:07.029386', 'London', 'UK', 'Pol (his first big indie show)', 'I Know The End', 'Phoebe Bridgers', 'Sad girl autumn, cathartic scream, communal grief', 'Reunion Tour', 'Alexandra Palace', 'MUNA, Christian Lee Hutson', 'Everyone screaming the I Know The End outro. Cathartic doesn''t begin to cover it.', 'MUNA were unreal too. Bought the Skeleton tour tee.', 'Full Punisher in order + Boygenius reunion encore with Lucy and Julien.', 'INDIE_ROCK', 'INDIE_POP', 'ARENA_TOUR', 'LARGE_VENUE', 'GENERAL_ADMISSION'),
(FALSE, 10, TRUE, DATE '2023-11-04', 165, 0, TRUE, 0.00, TRUE, 10, 5, 9, 28, FALSE, 90.00, 30.00, 10, 9, 1, TIMESTAMP '2026-06-25 13:28:07.031386', 4, TIMESTAMP '2026-06-25 13:28:07.031386', 'London', 'UK', 'Jake, Hanna, two strangers we met in the smoking area', 'Marea (we''ve lost dancing)', 'Fred again..', 'Euphoric, transcendent, phones-locked-up, full body sweat', 'Boiler Room x ConcertCrew', 'Printworks', 'Skrillex (b2b set)', 'The Skrillex b2b. Fred dropped Rumble unannounced. The whole crowd lost it.', 'Phone-free shows are how concerts should be. Found tickets day-of via the secret announce.', 'Yondr pouches at door. Best decision. Nobody filmed, everyone DANCED.', 'ELECTRONIC', 'HOUSE', 'SECRET_SHOW', 'LARGE_VENUE', 'STANDING_ONLY'),
(TRUE, 10, TRUE, DATE '2024-06-26', 140, 2, TRUE, 120.00, FALSE, 10, 5, 9, 20, FALSE, 180.00, 950.00, 10, 10, 1, TIMESTAMP '2026-06-25 13:28:07.033387', 5, TIMESTAMP '2026-06-25 13:28:07.033387', 'Tokyo', 'Japan', 'Ema (we flew to Tokyo for this)', 'Super Shy', 'NewJeans', 'Y2K kawaii, lightstick ocean, bunnies forever, jet-lagged but powering through', 'Bunnies Camp Tour', 'Tokyo Dome', NULL, 'The ETA stage with the entire dome in sync with the lightsticks.', 'Worth the flight. The Tokyo Dome lightstick coordination is unmatched.', 'Ditto + Hype Boy back-to-back was the killer combo. New choreography for Bubble Gum.', 'KPOP', 'POP', 'ARENA_TOUR', 'STADIUM', 'SEATED_FLOOR'),
(TRUE, 10, FALSE, DATE '2023-08-20', 75, 1, TRUE, 45.00, FALSE, 8, 5, 10, 14, TRUE, 75.00, 25.00, 10, 10, 1, TIMESTAMP '2026-06-25 13:28:07.034387', 6, TIMESTAMP '2026-06-25 13:28:07.034387', 'London', 'UK', 'Mia, Hanna, three other queer girls we met in line', 'Not Strong Enough', 'boygenius', 'Sapphic awakening, golden hour cry, friendship trio worship, communal', 'the rest tour', 'Gunnersbury Park', 'Ethel Cain, Muna', 'The three of them harmonizing on Letter To An Old Poet at golden hour.', 'Best summer afternoon of my life. Ethel Cain Preacher live = transcendent.', 'Full the record album + selections from the rest EP. Ethel Cain opener stole hearts.', 'INDIE_ROCK', 'INDIE_POP', 'FESTIVAL_SET', 'FESTIVAL_FIELD', 'FESTIVAL_FIELD');         
INSERT INTO "PUBLIC"."CONCERTS" VALUES
(FALSE, 8, FALSE, DATE '2024-04-18', 85, 2, FALSE, 28.00, TRUE, 10, 5, 10, 20, TRUE, 65.00, 18.00, 9, 10, 1, TIMESTAMP '2026-06-25 13:28:07.035385', 7, TIMESTAMP '2026-06-25 13:28:07.035385', 'London', 'UK', 'Solo (intentionally)', 'Last Words of a Shooting Star', 'Mitski', 'Theatrical, devastating, intimate-despite-2000-people, intentional', 'The Land Is Inhospitable Tour', 'Eventim Apollo', 'Madison Cunningham', 'Her choreographed movements during Washing Machine Heart. Visual poetry.', 'Went alone on purpose. Cried discreetly during ''I Bet on Losing Dogs''. Healing.', 'Phone-free policy was perfect. Mitski''s stage direction is unparalleled.', 'INDIE_ROCK', 'INDIE_POP', 'ARENA_TOUR', 'MID_VENUE', 'SEATED_LOWER'),
(TRUE, 10, TRUE, DATE '2024-07-05', 80, 0, FALSE, 50.00, FALSE, 9, 5, 10, 16, FALSE, 95.00, 25.00, 10, 9, 1, TIMESTAMP '2026-06-25 13:28:07.036385', 8, TIMESTAMP '2026-06-25 13:28:07.036385', 'London', 'UK', 'Mia, Jake, Pol (we all wore brat-green)', '365', 'Charli XCX', 'Brat summer, sweaty, lime-green tribalism, hyperpop euphoria', 'Brat Tour', 'Crystal Palace Park', 'Shygirl, A. G. Cook DJ set', 'Apple turned the entire field into one choreographed flash mob. Brat summer peaked.', 'This show defined the summer of 2024. Worth it just for the Apple choreo viral moment.', 'Full Brat in order + Track 10 + Vroom Vroom encore. A.G. Cook B2B was insane.', 'HYPERPOP', 'ELECTRONIC', 'FESTIVAL_SET', 'FESTIVAL_FIELD', 'FESTIVAL_FIELD'),
(FALSE, 10, TRUE, DATE '2024-05-23', 130, 1, TRUE, 0.00, FALSE, 10, 4, 8, 32, FALSE, 145.00, 280.00, 9, 8, 1, TIMESTAMP '2026-06-25 13:28:07.037386', 9, TIMESTAMP '2026-06-25 13:28:07.037386', 'Madrid', 'Spain', 'Hanna + her cousins from Madrid', 'Yo Perreo Sola', 'Bad Bunny', 'Perreo, latin trap takeover, summer in Madrid, sweaty euphoria', 'Most Wanted Tour', 'Estadio Olimpico', NULL, 'The mechanical bull rising during Monaco. Latin trap stadium chaos.', 'Stadium upper section is sketchy but the production made up for it. Hanna''s family fed us paella.', 'Heavy on nadie sabe + un verano sin ti cuts. Saturno trap deep cuts too.', 'RAP', 'HIP_HOP', 'STADIUM_TOUR', 'STADIUM', 'SEATED_UPPER'),
(FALSE, 7, FALSE, DATE '2024-02-09', 105, 1, TRUE, 25.00, FALSE, 7, 5, 9, 15, TRUE, 32.00, 12.00, 10, 10, 1, TIMESTAMP '2026-06-25 13:28:07.038386', 10, TIMESTAMP '2026-06-25 13:28:07.038386', 'London', 'UK', 'Pol (we both wept)', 'Turbines/Pigs', 'Black Country, New Road', 'Cathartic chamber-rock, post-Isaac era, communal silence, devastating', 'Live at Bush Hall Tour', 'EartH Hackney', 'Caroline', 'The brass section during The Boy. Post-rock at its absolute peak.', 'BCNR live is a different band than the records. The new era is even better. Bought the vinyl.', 'Almost entirely new material from Forever Howlong. Live At Bush Hall was incredible too.', 'INDIE_ROCK', 'FOLK', 'INTIMATE_VENUE', 'SMALL_CLUB', 'SEATED_FLOOR'); 
CREATE MEMORY TABLE "PUBLIC"."REFRESH_TOKENS"(
    "REVOKED" BOOLEAN NOT NULL,
    "EXPIRY_DATE" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "USER_ID" BIGINT NOT NULL,
    "TOKEN" CHARACTER VARYING(512) NOT NULL
);            
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4C" PRIMARY KEY("ID");             
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.REFRESH_TOKENS;          
INSERT INTO "PUBLIC"."REFRESH_TOKENS" VALUES
(FALSE, TIMESTAMP WITH TIME ZONE '2026-07-02 11:28:32.802423+00', 1, 1, '76580bc5-d176-4949-a20b-66ebd5da349a');
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ENABLED" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "REGISTERED_AT" TIMESTAMP(6) NOT NULL,
    "USERNAME" CHARACTER VARYING(50) NOT NULL,
    "EMAIL" CHARACTER VARYING(100) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLE" ENUM('ADMIN', 'USER') NOT NULL
);     
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D4" PRIMARY KEY("ID");      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(TRUE, 1, TIMESTAMP '2026-06-25 13:28:06.944365', 'admin', 'admin@concertcrew.hr', '$2a$10$olA7YrzpTEPrt73tjBVt/.F1jTHsB10pADrg3qrJfaH6qBkBpwfYq', 'ADMIN'),
(TRUE, 2, TIMESTAMP '2026-06-25 13:28:07.014385', 'user', 'user@concertcrew.hr', '$2a$10$OhZ1cwaLOmGIj7EPBz49wehhrAXz1bp2m11.6vKawuripB.J6Eml.', 'USER');  
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5CA" CHECK(("RATING" <= 5)
    AND ("RATING" >= 1)) NOCHECK;           
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE" CHECK(("DURATION_MINUTES" >= 0)
    AND ("DURATION_MINUTES" <= 600)) NOCHECK;        
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5" CHECK(("ENCORE_COUNT" <= 20)
    AND ("ENCORE_COUNT" >= 0)) NOCHECK;
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5C" CHECK(("PRODUCTION_SCORE" >= 1)
    AND ("PRODUCTION_SCORE" <= 10)) NOCHECK;       
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" CHECK(("CROWD_ENERGY_SCORE" >= 1)
    AND ("CROWD_ENERGY_SCORE" <= 10)) NOCHECK;      
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5CA8D_1" CHECK(("VOCAL_FORM_SCORE" >= 1)
    AND ("VOCAL_FORM_SCORE" <= 10)) NOCHECK;  
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5CA8D" CHECK(("SONGS_PLAYED" <= 100)
    AND ("SONGS_PLAYED" >= 0)) NOCHECK;           
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5CA8D_0" CHECK(("VIBE_SCORE" >= 1)
    AND ("VIBE_SCORE" <= 10)) NOCHECK;              
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BE5CA8" CHECK(("SETLIST_SCORE" >= 1)
    AND ("SETLIST_SCORE" <= 10)) NOCHECK;           
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("USERNAME");       
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" UNIQUE NULLS DISTINCT ("USER_ID");               
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C4" UNIQUE NULLS DISTINCT ("TOKEN");
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" UNIQUE NULLS DISTINCT ("EMAIL");         
ALTER TABLE "PUBLIC"."REFRESH_TOKENS" ADD CONSTRAINT "PUBLIC"."FK1LIH5Y2NPSF8U5O3VHDB9Y0OS" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."CONCERTS" ADD CONSTRAINT "PUBLIC"."FKB815KNI3O77S4MM2QSCPXLNR7" FOREIGN KEY("ADDED_BY_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;   
